
server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} : %msg%n"
  level:
    com.core.cashin: DEBUG

spring:
  # 1. Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/payments?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA/Hibernate Configuration
  jpa:
    show-sql: true # Log SQL statements
    hibernate:
      ddl-auto: none # Options: none, update, create, create-drop, validate
    properties:
      hibernate:
        # Specifies the MySQL Dialect for Hibernate
        dialect: org.hibernate.dialect.MySQLDialect

jobs:
  created-to-cancelled:
    cron: "0 0 */8 * * *"
  pending-to-cancel:
    cron: "0 0/10 0 */3 * *"
    zone: America/Mexico_City